Algoritmo "tabuada"
// 
//  
// Autor(a)    : Tharsila Borges Alves
// Data atual  : 25/05/2022
Var
// Seção de Declarações das variáveis 
numero, indice: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número para saber sua tabuada: ")
leia(numero)

para indice de 1 ate 10 faca
 escreva(numero, " x" ,indice, " =")
 escreval(numero * indice)
fimPara

Fimalgoritmo